project_id = "oxsxkwrsbpcmwghfmooz"

[functions.square-test-connection]
verify_jwt = false

[functions.sync-square-rewards]
verify_jwt = false

[functions.create-shopify-discount]
verify_jwt = false

[functions.auto-tag-products]
verify_jwt = false

[functions.test-shopify-config]
verify_jwt = false

[functions.update-product-tags]
verify_jwt = false

[functions.loyalty-lookup]
verify_jwt = false

[functions.loyalty-account]
verify_jwt = false

[functions.loyalty-redeem]
verify_jwt = false