# This file stores configuration for CLI commands.
# Docs: https://shopify.dev/docs/apps/build/cli-for-apps

name = "CheckoutLoyalty"
client_id = "your_client_id_here"
application_url = "https://your-deployed-project.lovableproject.com"
embedded = true

[access_scopes]
scopes = "write_products,read_customers,write_customers,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://your-deployed-project.lovableproject.com/auth/shopify/callback",
  "https://your-deployed-project.lovableproject.com/auth/tokens"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shop.woodcandleco.com"

[[app_extensions]]
name = "loyalty-cart"
handle = "loyalty-cart"