# This file stores configuration for CLI commands.
# Docs: https://shopify.dev/docs/apps/build/cli-for-apps

name = "Square Loyalty Integration"
client_id = ""
application_url = ""
embedded = true

[access_scopes]
scopes = "write_products,read_customers,write_customers,read_orders,write_orders"

[auth]
redirect_urls = [
  "/auth/shopify/callback",
  "/auth/tokens"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
