# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a28df600ba90f215cfff605e2b37c4e8"
name = "checkout-questions"
application_url = "https://shopify-square-points-rewards.lovable.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_customers,write_orders,write_products"

[auth]
redirect_urls = [ 
  "https://shopify-square-points-rewards.lovable.app/auth/shopify/callback",
  "https://shopify-square-points-rewards.lovable.app/auth/tokens"
]

# Extension configuration
[[app_extensions]]
name = "loyalty-cart"
handle = "loyalty-cart"