# This file stores configuration for CLI commands.
# Docs: https://shopify.dev/docs/apps/build/cli-for-apps

name = "CheckoutLoyalty"
client_id = "YOUR_NEW_CLIENT_ID_HERE"
application_url = "https://shopify-square-points-rewards.lovable.app"
embedded = true

[access_scopes]
scopes = "write_products,read_customers,write_customers,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://shopify-square-points-rewards.lovable.app/auth/shopify/callback",
  "https://shopify-square-points-rewards.lovable.app/auth/tokens"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shop.woodcandleco.com"
