// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxsxkwrsbpcmwghfmooz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94c3hrd3JzYnBjbXdnaGZtb296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjE2MzksImV4cCI6MjA3MzczNzYzOX0.re0nwcRGwcvwl8F3Eu1C1g-P3QEwOtNFpK6MGrlL7ek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});