name = "loyalty-checkout"
type = "checkout_ui_extension"

[[extensions.targeting]]
target = "purchase.checkout.block.render"

[extensions.capabilities]
network_access = true

[extensions.settings]
[[extensions.settings.fields]]
key = "square_app_id"
type = "single_line_text_field"
name = "Square Application ID"
description = "Your Square Application ID"

[[extensions.settings.fields]]
key = "square_access_token"
type = "single_line_text_field"
name = "Square Access Token"
description = "Your Square Access Token"